version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: mql-sandbox-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=store_db
    volumes:
      - mongo_data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

volumes:
  mongo_data:
