global:
  smtp_smarthost: "in-v3.mailjet.com:587"
  smtp_from: "info@cloudware.net.au"
  smtp_auth_username: ""
  smtp_auth_password: ""

route:
  receiver: main_receiver

  routes:
    - receiver: 'urgent_receiver'
      matchers:
      - severity="Critical"

receivers:
  - name: 'main_receiver'
    email_configs:
      - to: "baotochi87@gmail.com"
  - name: 'urgent_receiver'
    email_configs:
      - to: "baotochi87@gmail.com"